### PR TITLE
Fix spinner compatibility with file i/o

### LINKED ISSUE #67: Piping conflicts with spinner
I hit an issue while trying to pipe out to a text file. Our codebase is also using a spinner from the CLI library. I believe that I'm not in a position to share code, but here's the error dump I got:

vagrant@precise64:/vagrant/flh-etl$ node index > output.txt

/vagrant/flh-etl/modules/commandLineInterface/node_modules/cli/cli.js:1147
        stream.clearLine();
               ^
TypeError: Object #<SyncWriteStream> has no method 'clearLine'
    at null.<anonymous> (/vagrant/flh-etl/modules/commandLineInterface/node_modules/cli/cli.js:1147:16)
    at wrapper [as _onTimeout] (timers.js:258:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

### PR DESCRIPTION
**Pull request by KodeAndGame**
Attempting to resolve #67. Spinner will still output messages but will not try to animate.

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -1135,6 +1135,10 @@ cli.progress = function (progress, decimals, stream) {
 var spinnerInterval;
 cli.spinner = function (prefix, end, stream) {
     stream = stream || process.stdout;
+    if(!stream.clearLine) {
```
Comment (chriso) [inline cli.js]: You could probably use `if (!stream.isTTY)` here.

**Comment by chriso** [comment]
Thanks, this will work as-is I think.

File: cli.js (hunk 1 above)
Comment (KodeAndGame) [inline cli.js]: Ah that makes more sense and is what I was looking for. Thanks!
